21/08/21 (13:41:15) | ERROR: Data collection thread failed with exception: list index out of range
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2815, in _draw_fg
    vals += [f'{THEME.gradient["proc_color" if val < 100 else "process"][val if val < 100 else val - 100]}']
IndexError: list index out of range
21/08/21 (13:41:15) | WARNING: Exiting with errorcode (1). Runtime 0:00:01 

